name: safewaydirection
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.27+2
  cupertino_icons: ^0.1.2
  sliding_up_panel: ^1.0.2
  flutter_map: ^0.9.0
  cached_network_image: ^2.2.0+1
  latlong: ^0.6.1
  search_map_place: ^0.3.0
  flutter_polyline_points: ^0.2.2
  http: ^0.12.1
  sqflite: ^1.3.1
  path: ^1.6.4
  path_provider: ^1.6.11
  flutter_google_places: ^0.2.5
  adobe_xd: ^0.1.4
  dio: ^3.0.9
  location: ^3.0.2
  bubble: ^1.1.9+1
  geolocator: ^5.3.2+2
  rflutter_alert: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - image/_303.png
    - image/_304.png
    - image/KakaoTalk_20200709_214841133.png
    - image/currentLocation1.png
    - image/currentLocation2.png
    - image/currentLocation3.png
    - image/CurrentLocation.png
    - image/startMarker.png
    - image/endMarker.png
  fonts:
    - family: BMJUA
      fonts:
        - asset: fonts/BMJUA_ttf.ttf
