name: safewaydirection
description: finding safe routes for kids

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.27+2
  cupertino_icons: ^0.1.2
  search_map_place: ^0.3.0
  http: ^0.12.1
  sqflite: ^1.3.1
  path: ^1.6.4
  dio: ^3.0.9
  location: ^3.0.2
  bubble: ^1.1.9+1
  geolocator: ^5.3.2+2
  rflutter_alert: ^1.0.3
  carousel_slider: ^2.2.1
dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - image/kiki.png
    - image/myPin.png
    - image/CurrentLocation.png
    - image/startMarker.png
    - image/endMarker.png
    - image/crosswalk.png
    - image/firstpage_1.png
    - image/secondpage1.png
    - image/secondpage2.png
    - image/favoritepage.png
    - image/loadingpage.png
    - image/thirdpage1.png
    - image/thirdpage2.png

  fonts:
    - family: BMJUA
      fonts:
        - asset: fonts/BMJUA_ttf.ttf
